[package]
name = "quatopsy"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true
description = "Offline Quatopsy command-line interface."

[[bin]]
name = "quatopsy"
path = "src/main.rs"

[dependencies]
clap = { workspace = true }
ctrlc = { workspace = true }
quatopsy-adapt = { workspace = true }
quatopsy-core = { workspace = true }
quatopsy-plan = { workspace = true }
quatopsy-control = { workspace = true }
quatopsy-schema = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
